dir:
#  trainImgDir: 'D:/data/m2nist/minist_pics/'
#  trainAnnoDir: 'D:/data/m2nist/format_me/train_annotation/'
#  valAnnoDir: 'D:/data/m2nist/format_me/val_annotation/'
#  trainImgDir: '/media/q/deep/me/data/0digit/m2nist/format_orgin/images/'
#  trainAnnoDir: '/media/q/deep/me/data/0digit/m2nist/format_me/train_annotation/'
#  valAnnoDir: '/media/q/deep/me/data/0digit/m2nist/format_me/val_annotation/'

  trainImgDir: "/media/q/data/datasets/VOC/VOC2012/JPEGImages/"
  trainAnnoDir: "/media/q/data/datasets/VOC/VOC2012/format_me/Main/person/train/"
  valImgDir: "/media/q/data/datasets/VOC/VOC2007_test/JPEGImages/"
  valAnnoDir: "/media/q/data/datasets/VOC/VOC2007_test/format_me/Main/person/train/"
  modelSaveDir: '/media/q/deep/me/model/yolov1/'
  modelName : '100.pth'
  modelReloadFlag: 0
data:
  augment: False
  normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]] #[mean, std]
  imgChannelNumber: 3
model:
  netInput: (448, 448)
  featSize: (14, 14)
  stride : 32
  clsNum: 1
  bboxPredNum: 1
  imgChannelNumber: 3
loss:
  noobj: 0.5
  obj: 1

  cls: 1
  conf: 10
  box: 5
  l2: 0.0005
train:
  workers: 0
  batchSize: 14
  epoch: 300

  l2: 0.0005
  lr0: 0.003
  lrReduceFactor: 0.9
  lrReduceEpoch: 3    # N epoch, lr must  times lrReduceFactor
  lrPatience: 2 # train loss or val score will not improve, in N epoch
  warmupLr0: 0.00001
  warmupBatch: 10