dir:
#  trainImgDir: 'D:/data/m2nist/minist_pics/'
#  trainAnnoDir: 'D:/data/m2nist/format_me/train_annotation/'
#  valAnnoDir: 'D:/data/m2nist/format_me/val_annotation/'
  trainImgDir: '/media/q/deep/me/data/0digit/m2nist/format_orgin/images/'
  trainAnnoDir: '/media/q/deep/me/data/0digit/m2nist/format_me/train_annotation/'
  valAnnoDir: '/media/q/deep/me/data/0digit/m2nist/format_me/val_annotation/'
  modelSaveDir: '/media/q/deep/me/model/yolov1/'
  modelName : '35.pth'
  modelReloadFlag: True
data:
  augment: True
  normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]

model:
  netInput: (448, 448)
  featSize: (7, 7)
  stride : 64
  clsNum: 10
  bboxPredNum: 1
  imgChannelNumber: 3
loss:
  noobj: 0.05
  obj: 1
  cls: 1
train:
  workers: 8
  batchSize: 14
  epoch: 300
  l2: 0.0005
  lr0: 0.003
  warmupLr0: 0.00001
  warmupBatch: 100