clsname :
  {-1: "background", 0: 'aeroplane', 1: 'bicycle', 2: 'bird',3: 'boat',4: 'bottle',5: 'bus',
           6: 'car',7: 'cat',8: 'chair',9: 'cow',10: 'diningtable',
           11: 'dog',12: 'horse',13: 'motorbike',14: 'person',
           15: 'pottedplant',16: 'sheep',17: 'sofa',18: 'train',19: 'tvmonitor'}

dir:
#  trainImgDir: 'E:/code/other_data/onevoc/img/'
#  trainAnnoDir: 'E:/code/other_data/onevoc/anno/'
#  valImgDir: 'E:/code/other_data/onevoc/img/'
#  valAnnoDir: 'E:/code/other_data/onevoc/anno/'
#  modelSaveDir: '/media/q/deep/me/model/'

#  trainImgDir: "/media/q/data/datasets/VOC/VOC127/JPEGImages/"
#  trainAnnoDir: "/media/q/data/datasets/VOC/VOC127/format_me/Main/all/trainval_diff1/"
#  valImgDir: "/media/q/data/datasets/VOC/VOC127/JPEGImages/"
#  valAnnoDir: "/media/q/data/datasets/VOC/VOC127/format_me/Main/all/trainval_diff1/"
#  valImgDir: "/media/q/data/datasets/VOC/VOC2007_test/JPEGImages/"
#  valAnnoDir: "/media/q/data/datasets/VOC/VOC2007_test/format_me/Main/all/trainval_diff1/"
#  modelName : '680b.pth'
#  modelReloadFlag: 0

  modelSaveDir: '/media/q/deep/me/model/yolov1/weight/'
  logSaveDir: '/media/q/deep/me/model/yolov1/log/'
  trainImgDir: "/media/q/data/datasets/helmet/helm/images/train/"
  trainAnnoDir: "/media/q/data/datasets/helmet/helm/labels/train/"
  valImgDir: "/media/q/data/datasets/helmet/helm/images/valid/"
  valAnnoDir: "/media/q/data/datasets/helmet/helm/labels/train/"
#  modelNameSuffix: ""     #
  modelName : '680b.pth'
  modelReloadFlag: 0
data:
  augment: 1
  normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]] #[mean, std]
  imgChannelNumber: 3
  shuffle: 1

model:
  netInput: (448, 448) #hw
  featSize: (7, 7)
  stride : 64
  clsNum: 20
  bboxPredNum: 1
  imgChannelNumber: 3

loss:
  noobj: 0.025
  obj: 1

  cls: 1
  conf: 1
  box: 10
  l2: 0.00005

train:
  workers: 4
  batchSize: 16
  lr0: 0.0003 #0.00003
  warmupLr0: 0.000001
  warmupBatch: 1000

#default
  epoch: 30000
  lrReduceFactor: 1
  lrReduceEpoch: 1    # N epoch, lr must  times lrReduceFactor
  lrPatience: 2 # train loss or val score will not improve, in N epoch